### PR TITLE
Add Pagination and Reset Filters

### PR DESCRIPTION
**Pull request by gsavitha**

### CODE REVIEW

**Review by joshganguly — APPROVED** [review]
LGTM

**Comment by gsavitha** [comment]
Added pagination, results are rendered faster. Resolves #128

**Review by i-rahman — COMMENTED** [review]
Code LGTM - Reset Filter is resetting sort as well. Confirm WAI, otherwise will need fix
Also, Will have to do some code clean-up in the sprint

**Comment by gsavitha** [comment]
Removed Reset Sort. I agree that it may have been confusing from user perspective.

**Review by i-rahman — APPROVED** [review]
LGTM - Reset Filter now only resets filters. Sort remains.

**Review by gauravag2207 — APPROVED** [review]
Looks good.

**Pull request merged**
