### PR TITLE
Sign in

### LINKED ISSUE #18: As a registered Job seeker / Hiring Manager, I want to login to the application so that I am able to see to my personalized home page.
**User story**
As a registered Job seeker / Hiring Manager, I want to login to the application, so that I am able to see my account home page.

**Acceptance criteria**
- [x] The Sign In Page should have the following required fields
   - Email
   - Password
- [x] In the case of Invalid Email / Password, an error message “Invalid Username or Password” should pop up once the user clicks the Sign In button.
- [x] In case of valid information, the user should be redirected to his/her personalized page.

**Definition of Done**
- [x] Passed Unit Testing 
- [x] Code Review Completed 
- [x] Passed peer testing based on AC
- [x] Change Deployed to Production
- [x] Validated as working in Production

### PR DESCRIPTION
**Pull request by gsavitha**
Adds Sign In Functionality 
Resolves #18

### CODE REVIEW

**Comment by gauravag2207** [comment]
Reviewed.

**Comment by gauravag2207** [comment]
Reviewed and merged

**Review by gauravag2207 — COMMENTED** [review]
Reviewed. Looks good

**Comment by joshganguly** [comment]
linked to Epic #3

**Pull request merged**
