### PR TITLE
Merge Subscribe notify to Develop

### PR DESCRIPTION
**Pull request by gauravag2207**

### CODE REVIEW

**Review by shivangpandya — APPROVED** [review]
LGTM- Approved for merge

**Review by gsavitha — APPROVED** [review]
LGTM - Can be Merged.

**Review by joshganguly — APPROVED** [review]
LGTM ready to be merged into Develop

**Review by i-rahman — APPROVED** [review]
LGTM - reviewed code and tested locally. Can be merged

**Pull request merged**
