### PR TITLE
AboutUS page UI changes

### PR DESCRIPTION
**Pull request by joshganguly**
Added logos to AboutUS page

### CODE REVIEW

**Comment by joshganguly** [comment]
Looks like this -
On a larger screen:
 Screen Shot 2020-12-05 at 3 53 14 PM (2)
On a smaller screen:
Screen Shot 2020-12-05 at 3 53 14 PM

**Comment by joshganguly** [comment]
Now looks like this -
On a larger screen:
Screen Shot 2020-12-05 at 5 10 56 PM
On a smaller screen:
Screen Shot 2020-12-05 at 5 10 56 PM (2)

**Review by shivangpandya — APPROVED** [review]
LGTM- Ready for merge

**Review by i-rahman — COMMENTED** [review]
Approved

**Pull request merged**
