### PR TITLE
Add Sort, Filter, Apply and Favourite Jobs

### PR DESCRIPTION
**Pull request by gsavitha**
Adding features #70, #71, #47 , #48, #72

### CODE REVIEW

**Review by shivangpandya — APPROVED** [review]
Checked all the files for merge on main

**Review by i-rahman — APPROVED** [review]
LGTM - tested changes and can be merged with main

**Review by gauravag2207 — COMMENTED** [review]
Looks good to me. Working fine on staging

**Comment by joshganguly** [comment]
LGTM. Works fine on staging. Ready for production

**Pull request merged**
